In [1]:
import numpy as np

1. 1D NumPy array with integers from 1 to 20

In [2]:
arr = np.arange(1,21)
#a
print(arr.sum())
print(arr.mean())
print(np.median(arr)) #median method doesnt exist in the ndarray class:
print(arr.std())
#b
print(np.where(arr > 10)) #tuple output with a single element(ie array)

210
10.5
10.5
5.766281297335398
(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


2. 2D NumPy array of shape 4 X 4 with numbers ranging from 1 to 16.  

In [3]:
arr2 = np.arange(1,17).reshape(4,4)
print(arr2) #a
print(arr2.transpose()) #b
print("RowWise sum = ",arr2.sum(axis=1))      #c
print("ColumnWise sum = ",arr2.sum(axis=0))   #c

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
RowWise sum =  [10 26 42 58]
ColumnWise sum =  [28 32 36 40]


3. two 3 X 3 arrays filled with random integers between 1 and 20.

In [4]:
sqMtx1 = np.random.randint(1,20,9).reshape(3,3)
sqMtx2 = np.random.randint(1,20,9).reshape(3,3)
print(sqMtx1)
print(sqMtx2)
print(sqMtx1 + sqMtx2)
print(sqMtx1 - sqMtx2)
print(sqMtx1 * sqMtx2)
print(sqMtx1.dot(sqMtx2)) #there cant be a builtin op. (.)
#coz it has diff meaning in programming

[[11  7  5]
 [14  4 19]
 [ 8 16 18]]
[[12  6 11]
 [16 14  1]
 [13 16  8]]
[[23 13 16]
 [30 18 20]
 [21 32 26]]
[[ -1   1  -6]
 [ -2 -10  18]
 [ -5   0  10]]
[[132  42  55]
 [224  56  19]
 [104 256 144]]
[[309 244 168]
 [479 444 310]
 [586 560 248]]


4. 1D array of size 12 & then reshape to 3x4

In [20]:
arr4 = np.arange(1,13)
arr4 = arr4.reshape(3,4) #Now its 2D
print(arr4[0:2 , -2:])

[[3 4]
 [7 8]]
